title: "[Announcement] "
labels:
  - announcement
body:
  - type: markdown
    attributes:
      value: |
        Official announcements and updates about ExpellusAI.
  - type: textarea
    id: announcement
    attributes:
      label: Announcement
      description: What's new?
    validations:
      required: true
